# This job includes coverage
name: test-environment
channels:
  - conda-forge
dependencies:
  # required dependencies
  - python=3.7.*
  - numpy=1.17.*
  - pandas=0.25.*
  # test dependencies
  - pytest
  - pytest-xdist
  - moto>=1.3.14
  - flask
  - fastparquet
  - h5py
  - pytables
  - zarr
  - tiledb-py
  - fsspec>=0.6.0
  - sqlalchemy
  # Remove <2 version constraint once we've added pyarrow 2.0 compatibility
  # xref https://github.com/dask/dask/issues/6754
  - pyarrow>=0.14.0,<2
  - coverage
  - jsonschema
  # other -- IO
  - bcolz
  - blosc
  - boto3
  - botocore
  - aiohttp
  - bokeh
  - httpretty
  - chest
  - s3fs
  - cloudpickle
  - crick
  - cytoolz
  - distributed
  - graphviz
  - ipython
  - lz4
  - numba
  - partd
  - pickle5
  - psutil
  - requests
  - scikit-image
  - scikit-learn
  - scipy
  - toolz
  - python-snappy
  - sparse
  - cachey
  - python-graphviz
  - pandas-datareader
  - python-xxhash
  - mmh3
  - pip
